stages:
  - deploy

variables:
  APP_NAME: todovoodoo

deploy:
  image: ilyasemenov/gitlab-ci-git-push
  stage: deploy
  environment:
    name: production
    url: https://$TODOVOODO_HOST/
  only:
    - master
  script:
    - git-push ssh://dokku@$DOKKU_HOST:22/$APP_NAME