# Generated by Django 2.2 on 2019-05-09 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("core", "0002_add_public_id")]

    operations = [
        migrations.AddField(
            model_name="listitem", name="always_show", field=models.BooleanField(default=False)
        )
    ]
