# Generated by Django 2.2.5 on 2019-09-04 01:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_listitem_always_show'),
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('pub_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Publicly viewable station identifier.', unique=True)),
                ('name', models.TextField(default='New Station', help_text="Name of the station. (e.g.'Towel Station', 'Bathroom')")),
                ('description', models.TextField(blank=True, help_text="Description of what to include in a report entry. (e.g. 'take a picture of the towels')'")),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReportEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('description', models.TextField(blank=True, help_text='Description of the state of the current state of the station.')),
                ('photo_upload', models.FileField(help_text='Photo taken of the station.', null=True, upload_to='')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text="Reporter's phone number.", max_length=128, region=None)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Station')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
