# Generated by Django 2.2.6 on 2019-10-11 05:48

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [("core", "0006_auto_20190928_0008")]

    operations = [
        migrations.AddField(
            model_name="station",
            name="slug",
            field=django_extensions.db.fields.AutoSlugField(
                blank=True, editable=False, populate_from=["name", "owner__name"]
            ),
        )
    ]
