# Generated by Django 2.2.6 on 2019-10-12 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("core", "0008_auto_20191011_0006")]

    operations = [
        migrations.AlterField(
            model_name="reportentry",
            name="photo_upload",
            field=models.ImageField(
                help_text="Photo taken of the station.", null=True, upload_to=""
            ),
        )
    ]
