# Generated by Django 2.2.6 on 2019-11-04 09:04

from django.db import migrations, models
import todovoodoo.core.models


class Migration(migrations.Migration):

    dependencies = [("core", "0010_auto_20191103_2238")]

    operations = [
        migrations.AlterField(
            model_name="reportentry",
            name="photo_upload",
            field=models.ImageField(
                help_text="Photo taken of the station.",
                null=True,
                upload_to=todovoodoo.core.models.get_file_path,
            ),
        )
    ]
