# Generated by Django 2.2.7 on 2020-03-30 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("core", "0011_auto_20191104_0104")]

    operations = [
        migrations.AddField(
            model_name="reportentry",
            name="report_type",
            field=models.TextField(
                choices=[("checkout", "Check-Out"), ("checkin", "Check-In"), ("other", "Other")],
                default="other",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="station",
            name="station_type",
            field=models.TextField(
                choices=[("standard", "Standard"), ("checkin", "Check-In/Check-Out")],
                default="standard",
                null=True,
            ),
        ),
    ]
