# Generated by Django 2.1.3 on 2018-11-22 21:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(model_name="todolist", name="name", field=models.TextField()),
        migrations.AlterUniqueTogether(name="todolist", unique_together={("owner", "name")}),
    ]
