# Generated by Django 2.1.3 on 2018-11-28 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("core", "0002_auto_20181122_2132")]

    operations = [
        migrations.AddField(
            model_name="todolist",
            name="date_unit",
            field=models.CharField(
                choices=[
                    ("days", "days"),
                    ("weeks", "weeks"),
                    ("months", "months"),
                    ("years", "years"),
                ],
                default="weeks",
                max_length=8,
            ),
        ),
        migrations.AddField(
            model_name="todolist", name="interval_duration", field=models.IntegerField(default=1)
        ),
    ]
